<!DOCTYPE html>
<html>

<head>
    <title>Sales Report</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            padding: 20px;
            font-size: 12px;
        }

        h1 {
            color: #800000;
            border-bottom: 3px solid #FFD700;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .stats-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        .stat-box {
            flex: 1;
            padding: 15px;
            background: #fff;
            border: 1px solid #ddd;
            text-align: center;
            margin-right: 10px;
        }

        .stat-box:last-child {
            margin-right: 0;
        }

        .stat-label {
            color: #666;
            font-size: 10px;
            text-transform: uppercase;
        }

        .stat-value {
            color: #800000;
            font-size: 18px;
            font-weight: bold;
            margin-top: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background: #800000;
            color: #fff;
            padding: 10px;
            text-align: left;
            font-size: 11px;
        }

        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
            font-size: 11px;
        }

        .top-products {
            margin-top: 20px;
            page-break-inside: avoid;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            color: #999;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
    </style>
</head>

<body>
    <h1>Sales Report - {{ $user->name }}</h1>

    <div class="header-info">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}<br>
        <strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}
    </div>

    <div class="stats-row">
        <div class="stat-box">
            <div class="stat-label">Total Revenue</div>
            <div class="stat-value">P{{ number_format($totalRevenue, 2) }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Items Sold</div>
            <div class="stat-value">{{ number_format($totalItems) }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Transactions</div>
            <div class="stat-value">{{ number_format($totalTransactions) }}</div>
        </div>
    </div>

    <div class="top-products">
        <h3 style="color:#800000; margin-bottom:10px;">Top Selling Products</h3>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Product</th>
                    <th style="text-align:center;">Qty Sold</th>
                    <th style="text-align:right;">Revenue</th>
                </tr>
            </thead>
            <tbody>
                @foreach($topProducts as $index => $product)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td><strong>{{ $product['name'] }}</strong></td>
                    <td style="text-align:center;">{{ $product['quantity'] }}</td>
                    <td style="text-align:right;">P{{ number_format($product['revenue'], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div style="margin-top:30px;">
        <h3 style="color:#800000; margin-bottom:10px;">All Transactions</h3>
        <table>
            <thead>
                <tr>
                    <th>Date & Time</th>
                    <th>Product</th>
                    <th style="text-align:center;">Qty</th>
                    <th style="text-align:right;">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($sales as $sale)
                <tr>
                    <td>{{ $sale->created_at->format('M d, Y h:i A') }}</td>
                    <td>{{ $sale->product->name }}</td>
                    <td style="text-align:center;">{{ $sale->quantity }}</td>
                    <td style="text-align:right;">P{{ number_format($sale->total, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by StreetPOS - Your Filipino Street Food Business Companion
    </div>
</body>

</html>